# Generated by Django 5.2.5 on 2026-06-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('presentation', 'Presentation'), ('essay', 'Essay'), ('report', 'Report'), ('poster', 'Poster')], max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], default='standard', max_length=20)),
                ('slides', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('in_progress', 'İcradadır'), ('completed', 'Tamamlandı'), ('delivered', 'Çatdırıldı')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
