# Generated by Django 5.2.5 on 2026-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='content_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='content_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
