# Generated by Django 5.2.5 on 2026-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_type_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/previews/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
